### ISSUE TITLE
typo "delete" instead of "create"

### ISSUE THREAD

**Issue by odyright** [WilliamTakeshi/elixir_reasonml_food_delivery_service#1]
https://github.com/WilliamTakeshi/elixir_reasonml_food_delivery_service/blob/2d6dcdd3674124c2f2e8b6a42647409236494e5d/backend/lib/food_delivery/policy.ex#L51

**Comment by WilliamTakeshi** [comment]
Thanks for the comment. If you want you can send me a PR and I will be happy to accept.

There is others comments error that I see in this file if you wanna help :)
